// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { BylineSummary, ContentBylineCredit, TaxonomyTerm } from "emdash";

export interface CommunityProject {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  project_status?: "Planning" | "In Progress" | "Complete";
  group?: "home" | "recipient_2026";
  description?: string;
  image?: string;
  image_alt?: string;
  quote?: string;
  quote_cite?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface FiscalYear {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  amount: number;
  community_amount: number;
  period_note?: string;
  community_note?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Project {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  summary?: string;
  intro?: string;
  card_status?: "Planning" | "In Progress" | "Complete";
  detail_status?: "Planning" | "In Progress" | "Complete";
  allocated: number;
  goals?: unknown;
  milestones?: unknown;
  yearly_spend?: unknown;
  card_image?: string;
  card_image_alt?: string;
  photo?: string;
  photo_alt?: string;
  meta_title?: string;
  meta_description?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    community_projects: CommunityProject;
    fiscal_years: FiscalYear;
    projects: Project;
  }
}